pacdiff: don't assume the DBPath has a trailing slash
If pacman-conf returns a DBPath without a trailing slash, then the
script will error out with:

ERROR: unable to read pacman database /var/lib/pacmanlocal

Which is obviously wrong.

Signed-off-by: Eli Schwartz <eschwartz@archlinux.org>